arb-dir: lib/l10n
template-arb-file: app_vi.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
# QUAN TRỌNG: đừng để synthetic-package: false nếu bạn muốn import package:flutter_gen
